--------------------------------------------------------
--  파일이 생성됨 - 금요일-5월-01-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence CHAIN_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ADMIN"."CHAIN_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MENUOPTION_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ADMIN"."MENUOPTION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MENU_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ADMIN"."MENU_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence POST_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ADMIN"."POST_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence QNA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ADMIN"."QNA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence RESERVATION_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ADMIN"."RESERVATION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SHOPINFO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ADMIN"."SHOPINFO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ACCOUNT
--------------------------------------------------------

  CREATE TABLE "ADMIN"."ACCOUNT" 
   (	"BUSINESSNUMBER" NUMBER, 
	"PASSWORD" VARCHAR2(40 BYTE), 
	"EMAIL" VARCHAR2(40 BYTE), 
	"PHONE" NUMBER, 
	"EMAILACCEPT" VARCHAR2(20 BYTE), 
	"SMSACCEPT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "ADMIN"."ACCOUNT"."BUSINESSNUMBER" IS '사업자번호';
   COMMENT ON COLUMN "ADMIN"."ACCOUNT"."PASSWORD" IS '비밀번호';
   COMMENT ON COLUMN "ADMIN"."ACCOUNT"."EMAIL" IS '이메일';
   COMMENT ON COLUMN "ADMIN"."ACCOUNT"."PHONE" IS '연락처';
   COMMENT ON COLUMN "ADMIN"."ACCOUNT"."EMAILACCEPT" IS '이메일수신여부';
   COMMENT ON COLUMN "ADMIN"."ACCOUNT"."SMSACCEPT" IS '문자수신여부';
   COMMENT ON TABLE "ADMIN"."ACCOUNT"  IS '사업자 계정 테이블';
--------------------------------------------------------
--  DDL for Table CHAINS
--------------------------------------------------------

  CREATE TABLE "ADMIN"."CHAINS" 
   (	"CHAINNAME" VARCHAR2(20 BYTE), 
	"CHAINIMAGE" VARCHAR2(400 BYTE), 
	"CHAINDESC" VARCHAR2(1000 BYTE), 
	"SID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "ADMIN"."CHAINS"."CHAINNAME" IS '체인명';
   COMMENT ON COLUMN "ADMIN"."CHAINS"."CHAINIMAGE" IS '체인이미지';
   COMMENT ON COLUMN "ADMIN"."CHAINS"."CHAINDESC" IS '체인설명';
   COMMENT ON COLUMN "ADMIN"."CHAINS"."SID" IS 'SID';
--------------------------------------------------------
--  DDL for Table MENU
--------------------------------------------------------

  CREATE TABLE "ADMIN"."MENU" 
   (	"MENUNAME" VARCHAR2(20 BYTE), 
	"MENUPRICE" NUMBER, 
	"MENUIMAGE" VARCHAR2(400 BYTE), 
	"MENUDESC" VARCHAR2(1000 BYTE), 
	"MENUCATEGORY" VARCHAR2(20 BYTE), 
	"SHOPNAME" VARCHAR2(20 BYTE), 
	"BUSINESSNUMBER" NUMBER, 
	"SID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "ADMIN"."MENU"."MENUNAME" IS '메뉴이름';
   COMMENT ON COLUMN "ADMIN"."MENU"."MENUPRICE" IS '메뉴가격';
   COMMENT ON COLUMN "ADMIN"."MENU"."MENUIMAGE" IS '메뉴이미지';
   COMMENT ON COLUMN "ADMIN"."MENU"."MENUDESC" IS '메뉴설명';
   COMMENT ON COLUMN "ADMIN"."MENU"."MENUCATEGORY" IS '메뉴분류';
   COMMENT ON COLUMN "ADMIN"."MENU"."SHOPNAME" IS '상점이름';
   COMMENT ON COLUMN "ADMIN"."MENU"."BUSINESSNUMBER" IS '사업자번호';
   COMMENT ON COLUMN "ADMIN"."MENU"."SID" IS 'SID';
--------------------------------------------------------
--  DDL for Table MENUOPTION
--------------------------------------------------------

  CREATE TABLE "ADMIN"."MENUOPTION" 
   (	"OPTIONNAME" VARCHAR2(20 BYTE), 
	"MENUNAME" VARCHAR2(20 BYTE), 
	"MENUSID" NUMBER, 
	"OPTIONPRICE" NUMBER, 
	"OPTIONSID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "ADMIN"."MENUOPTION"."OPTIONNAME" IS '옵션이름';
   COMMENT ON COLUMN "ADMIN"."MENUOPTION"."MENUNAME" IS '메뉴이름';
   COMMENT ON COLUMN "ADMIN"."MENUOPTION"."MENUSID" IS '메뉴참조';
   COMMENT ON COLUMN "ADMIN"."MENUOPTION"."OPTIONPRICE" IS '옵션가격';
   COMMENT ON COLUMN "ADMIN"."MENUOPTION"."OPTIONSID" IS 'SID';
--------------------------------------------------------
--  DDL for Table POST
--------------------------------------------------------

  CREATE TABLE "ADMIN"."POST" 
   (	"WRITERNAME" VARCHAR2(20 BYTE), 
	"WRITERPHONE" NUMBER, 
	"MARK" VARCHAR2(20 BYTE), 
	"POSTCONTENT" VARCHAR2(1000 BYTE), 
	"WRITEDATE" DATE, 
	"SHOPNAME" VARCHAR2(20 BYTE), 
	"BUSINESSNUMBER" NUMBER, 
	"POSTREPLY" VARCHAR2(1000 BYTE), 
	"SID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "ADMIN"."POST"."WRITERNAME" IS '작성자이름';
   COMMENT ON COLUMN "ADMIN"."POST"."WRITERPHONE" IS '작성자연락처';
   COMMENT ON COLUMN "ADMIN"."POST"."MARK" IS '평점';
   COMMENT ON COLUMN "ADMIN"."POST"."POSTCONTENT" IS '후기내용';
   COMMENT ON COLUMN "ADMIN"."POST"."WRITEDATE" IS '작성날짜';
   COMMENT ON COLUMN "ADMIN"."POST"."SHOPNAME" IS '상점이름';
   COMMENT ON COLUMN "ADMIN"."POST"."BUSINESSNUMBER" IS '사업자번호';
   COMMENT ON COLUMN "ADMIN"."POST"."POSTREPLY" IS '후기답변';
   COMMENT ON COLUMN "ADMIN"."POST"."SID" IS 'SID';
--------------------------------------------------------
--  DDL for Table QNA
--------------------------------------------------------

  CREATE TABLE "ADMIN"."QNA" 
   (	"WRITERNAME" VARCHAR2(20 BYTE), 
	"WRITERPHONE" VARCHAR2(20 BYTE), 
	"TITLE" VARCHAR2(100 BYTE), 
	"WRITEDATE" VARCHAR2(20 BYTE), 
	"CONTENT" VARCHAR2(1000 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"REPLYCONTENT" VARCHAR2(1000 BYTE), 
	"REPLYDATE" VARCHAR2(20 BYTE), 
	"SID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "ADMIN"."QNA"."WRITERNAME" IS '작성자이름';
   COMMENT ON COLUMN "ADMIN"."QNA"."WRITERPHONE" IS '작성자연락처';
   COMMENT ON COLUMN "ADMIN"."QNA"."TITLE" IS '제목';
   COMMENT ON COLUMN "ADMIN"."QNA"."WRITEDATE" IS '작성날짜';
   COMMENT ON COLUMN "ADMIN"."QNA"."CONTENT" IS '질문내용';
   COMMENT ON COLUMN "ADMIN"."QNA"."PASSWORD" IS '글비밀번호';
   COMMENT ON COLUMN "ADMIN"."QNA"."REPLYCONTENT" IS '답변내용';
   COMMENT ON COLUMN "ADMIN"."QNA"."REPLYDATE" IS '답변날짜';
   COMMENT ON COLUMN "ADMIN"."QNA"."SID" IS 'SID';
--------------------------------------------------------
--  DDL for Table RESERVATION
--------------------------------------------------------

  CREATE TABLE "ADMIN"."RESERVATION" 
   (	"NAME" VARCHAR2(20 BYTE), 
	"PHONE" NUMBER, 
	"SHOPNAME" VARCHAR2(20 BYTE), 
	"BUSINESSNUMBER" NUMBER, 
	"RESRVATIONMENU" VARCHAR2(20 BYTE), 
	"RESERVATIONTIME" VARCHAR2(20 BYTE), 
	"RESERVATIONDATE" VARCHAR2(20 BYTE), 
	"SID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "ADMIN"."RESERVATION"."NAME" IS '예약자이름';
   COMMENT ON COLUMN "ADMIN"."RESERVATION"."PHONE" IS '예약자 핸드폰 번호';
   COMMENT ON COLUMN "ADMIN"."RESERVATION"."SHOPNAME" IS '가게명';
   COMMENT ON COLUMN "ADMIN"."RESERVATION"."BUSINESSNUMBER" IS '사업자번호';
   COMMENT ON COLUMN "ADMIN"."RESERVATION"."RESRVATIONMENU" IS '예약메뉴명';
   COMMENT ON COLUMN "ADMIN"."RESERVATION"."RESERVATIONTIME" IS '예약시간';
   COMMENT ON COLUMN "ADMIN"."RESERVATION"."RESERVATIONDATE" IS '예약날짜';
   COMMENT ON COLUMN "ADMIN"."RESERVATION"."SID" IS 'SID
';
--------------------------------------------------------
--  DDL for Table SHOPINFO
--------------------------------------------------------

  CREATE TABLE "ADMIN"."SHOPINFO" 
   (	"SHOPNAME" VARCHAR2(20 BYTE), 
	"BUSINESSNUMBER" NUMBER, 
	"SHOPADDRESS" VARCHAR2(400 BYTE), 
	"SHOPPHONE" NUMBER, 
	"SHOPCATEGORY" VARCHAR2(20 BYTE), 
	"SHOPINFO" VARCHAR2(1000 BYTE), 
	"SHOPCHAINNAME" VARCHAR2(20 BYTE), 
	"SHOPMARK" VARCHAR2(20 BYTE), 
	"SHOPIMAGE" VARCHAR2(400 BYTE), 
	"SID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "ADMIN"."SHOPINFO"."SHOPNAME" IS '상점이름';
   COMMENT ON COLUMN "ADMIN"."SHOPINFO"."BUSINESSNUMBER" IS '사업자번호';
   COMMENT ON COLUMN "ADMIN"."SHOPINFO"."SHOPADDRESS" IS '상점주소';
   COMMENT ON COLUMN "ADMIN"."SHOPINFO"."SHOPPHONE" IS '상점연락처';
   COMMENT ON COLUMN "ADMIN"."SHOPINFO"."SHOPCATEGORY" IS '상점분류';
   COMMENT ON COLUMN "ADMIN"."SHOPINFO"."SHOPINFO" IS '상점설명';
   COMMENT ON COLUMN "ADMIN"."SHOPINFO"."SHOPCHAINNAME" IS '체인점이름';
   COMMENT ON COLUMN "ADMIN"."SHOPINFO"."SHOPMARK" IS '상점평점';
   COMMENT ON COLUMN "ADMIN"."SHOPINFO"."SHOPIMAGE" IS '상점이미지';
   COMMENT ON COLUMN "ADMIN"."SHOPINFO"."SID" IS 'SID';
REM INSERTING into ADMIN.ACCOUNT
SET DEFINE OFF;
Insert into ADMIN.ACCOUNT (BUSINESSNUMBER,PASSWORD,EMAIL,PHONE,EMAILACCEPT,SMSACCEPT) values (12345,'1234','alliswell1618@nate.com',1041147122,'yes','yes');
REM INSERTING into ADMIN.CHAINS
SET DEFINE OFF;
Insert into ADMIN.CHAINS (CHAINNAME,CHAINIMAGE,CHAINDESC,SID) values ('이름','이미지 경로','설명',6);
Insert into ADMIN.CHAINS (CHAINNAME,CHAINIMAGE,CHAINDESC,SID) values ('이름2','이미지 경로','설명',8);
REM INSERTING into ADMIN.MENU
SET DEFINE OFF;
REM INSERTING into ADMIN.MENUOPTION
SET DEFINE OFF;
REM INSERTING into ADMIN.POST
SET DEFINE OFF;
REM INSERTING into ADMIN.QNA
SET DEFINE OFF;
Insert into ADMIN.QNA (WRITERNAME,WRITERPHONE,TITLE,WRITEDATE,CONTENT,PASSWORD,REPLYCONTENT,REPLYDATE,SID) values ('고길동','010-****-****','궁금함','2015.5.1','ㅁ니럼ㄴ이러ㅣㄴ린이러ㅣㅁㄴ어림ㄴㅇ리ㅓㄴ이런','1234','ㅁㄴㅇㄻㄴㅇㄻㄴㅇㄻㄴㅇㄻㄴㅇㄹ','2015.5.2',1);
Insert into ADMIN.QNA (WRITERNAME,WRITERPHONE,TITLE,WRITEDATE,CONTENT,PASSWORD,REPLYCONTENT,REPLYDATE,SID) values ('홍길동','010-****-****','문의함','2015.4.30','ㅁㄴ이러ㅣㅏ넝리ㅏㅓ니러닝러ㅏㅣㅁㄴ어리ㅏㅓ','1234','1ㅁㄴㅇㄹㄴㅁㅇㄹㄴㅁㅇㄹㄴㅁㅇㄹㄴㅇ','2015.5.2',4);
REM INSERTING into ADMIN.RESERVATION
SET DEFINE OFF;
REM INSERTING into ADMIN.SHOPINFO
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index CHAINS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."CHAINS_PK" ON "ADMIN"."CHAINS" ("CHAINNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MENU_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."MENU_PK" ON "ADMIN"."MENU" ("SID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index QNA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."QNA_PK" ON "ADMIN"."QNA" ("SID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ACCOUNT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."ACCOUNT_PK" ON "ADMIN"."ACCOUNT" ("BUSINESSNUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SHOPINFO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SHOPINFO_PK" ON "ADMIN"."SHOPINFO" ("BUSINESSNUMBER", "SHOPNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MENUOPTION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."MENUOPTION_PK" ON "ADMIN"."MENUOPTION" ("OPTIONSID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RESERVATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."RESERVATION_PK" ON "ADMIN"."RESERVATION" ("SID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index POST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."POST_PK" ON "ADMIN"."POST" ("SID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ACCOUNT
--------------------------------------------------------

  ALTER TABLE "ADMIN"."ACCOUNT" MODIFY ("SMSACCEPT" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."ACCOUNT" MODIFY ("EMAILACCEPT" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."ACCOUNT" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."ACCOUNT" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."ACCOUNT" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."ACCOUNT" ADD CONSTRAINT "ACCOUNT_PK" PRIMARY KEY ("BUSINESSNUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ADMIN"."ACCOUNT" MODIFY ("BUSINESSNUMBER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table QNA
--------------------------------------------------------

  ALTER TABLE "ADMIN"."QNA" ADD CONSTRAINT "QNA_PK" PRIMARY KEY ("SID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ADMIN"."QNA" MODIFY ("SID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."QNA" MODIFY ("REPLYDATE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."QNA" MODIFY ("REPLYCONTENT" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."QNA" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."QNA" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."QNA" MODIFY ("WRITEDATE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."QNA" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."QNA" MODIFY ("WRITERPHONE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."QNA" MODIFY ("WRITERNAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SHOPINFO
--------------------------------------------------------

  ALTER TABLE "ADMIN"."SHOPINFO" MODIFY ("SID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SHOPINFO" ADD CONSTRAINT "SHOPINFO_PK" PRIMARY KEY ("BUSINESSNUMBER", "SHOPNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ADMIN"."SHOPINFO" MODIFY ("SHOPIMAGE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SHOPINFO" MODIFY ("SHOPMARK" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SHOPINFO" MODIFY ("SHOPCHAINNAME" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SHOPINFO" MODIFY ("SHOPINFO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SHOPINFO" MODIFY ("SHOPCATEGORY" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SHOPINFO" MODIFY ("SHOPPHONE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SHOPINFO" MODIFY ("SHOPADDRESS" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SHOPINFO" MODIFY ("BUSINESSNUMBER" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SHOPINFO" MODIFY ("SHOPNAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MENUOPTION
--------------------------------------------------------

  ALTER TABLE "ADMIN"."MENUOPTION" ADD CONSTRAINT "MENUOPTION_PK" PRIMARY KEY ("OPTIONSID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ADMIN"."MENUOPTION" MODIFY ("OPTIONSID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MENUOPTION" MODIFY ("MENUSID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MENUOPTION" MODIFY ("OPTIONPRICE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MENUOPTION" MODIFY ("MENUNAME" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MENUOPTION" MODIFY ("OPTIONNAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESERVATION
--------------------------------------------------------

  ALTER TABLE "ADMIN"."RESERVATION" ADD CONSTRAINT "RESERVATION_PK" PRIMARY KEY ("SID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ADMIN"."RESERVATION" MODIFY ("SID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."RESERVATION" MODIFY ("RESERVATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."RESERVATION" MODIFY ("RESERVATIONTIME" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."RESERVATION" MODIFY ("RESRVATIONMENU" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."RESERVATION" MODIFY ("BUSINESSNUMBER" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."RESERVATION" MODIFY ("SHOPNAME" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."RESERVATION" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."RESERVATION" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table POST
--------------------------------------------------------

  ALTER TABLE "ADMIN"."POST" ADD CONSTRAINT "POST_PK" PRIMARY KEY ("SID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ADMIN"."POST" MODIFY ("SID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."POST" MODIFY ("POSTREPLY" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."POST" MODIFY ("BUSINESSNUMBER" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."POST" MODIFY ("SHOPNAME" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."POST" MODIFY ("WRITEDATE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."POST" MODIFY ("POSTCONTENT" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."POST" MODIFY ("MARK" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."POST" MODIFY ("WRITERPHONE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."POST" MODIFY ("WRITERNAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CHAINS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."CHAINS" MODIFY ("SID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."CHAINS" ADD CONSTRAINT "CHAINS_PK" PRIMARY KEY ("CHAINNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ADMIN"."CHAINS" MODIFY ("CHAINDESC" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."CHAINS" MODIFY ("CHAINIMAGE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."CHAINS" MODIFY ("CHAINNAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MENU
--------------------------------------------------------

  ALTER TABLE "ADMIN"."MENU" ADD CONSTRAINT "MENU_PK" PRIMARY KEY ("SID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ADMIN"."MENU" MODIFY ("SID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MENU" MODIFY ("BUSINESSNUMBER" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MENU" MODIFY ("SHOPNAME" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MENU" MODIFY ("MENUCATEGORY" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MENU" MODIFY ("MENUDESC" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MENU" MODIFY ("MENUIMAGE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MENU" MODIFY ("MENUPRICE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MENU" MODIFY ("MENUNAME" NOT NULL ENABLE);
--------------------------------------------------------
--  DDL for Trigger CHAINS_AUTOINCREMENT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ADMIN"."CHAINS_AUTOINCREMENT" 
   before insert on "ADMIN"."CHAINS" 
   for each row 
begin  
   if inserting then 
      if :NEW."SID" is null then 
         select CHAIN_SEQ.nextval into :NEW."SID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "ADMIN"."CHAINS_AUTOINCREMENT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MENUOPTION_AUTOINCREMENT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ADMIN"."MENUOPTION_AUTOINCREMENT" 
   before insert on "ADMIN"."MENUOPTION" 
   for each row 
begin  
   if inserting then 
      if :NEW."OPTIONSID" is null then 
         select MENUOPTION_SEQ.nextval into :NEW."OPTIONSID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "ADMIN"."MENUOPTION_AUTOINCREMENT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MENU_AUTOINCREMENT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ADMIN"."MENU_AUTOINCREMENT" 
   before insert on "ADMIN"."MENU" 
   for each row 
begin  
   if inserting then 
      if :NEW."SID" is null then 
         select MENU_SEQ.nextval into :NEW."SID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "ADMIN"."MENU_AUTOINCREMENT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger POST_AUTOINCREMENT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ADMIN"."POST_AUTOINCREMENT" 
   before insert on "ADMIN"."POST" 
   for each row 
begin  
   if inserting then 
      if :NEW."SID" is null then 
         select POST_SEQ.nextval into :NEW."SID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "ADMIN"."POST_AUTOINCREMENT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger QNA_AUTOINCREMENT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ADMIN"."QNA_AUTOINCREMENT" 
   before insert on "ADMIN"."QNA" 
   for each row 
begin  
   if inserting then 
      if :NEW."SID" is null then 
         select QNA_SEQ.nextval into :NEW."SID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "ADMIN"."QNA_AUTOINCREMENT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger RESERVATION_AUTOINCREMENT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ADMIN"."RESERVATION_AUTOINCREMENT" 
   before insert on "ADMIN"."RESERVATION" 
   for each row 
begin  
   if inserting then 
      if :NEW."SID" is null then 
         select RESERVATION_SEQ.nextval into :NEW."SID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "ADMIN"."RESERVATION_AUTOINCREMENT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SHOPINFO_INCREMENT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ADMIN"."SHOPINFO_INCREMENT" 
   before insert on "ADMIN"."SHOPINFO" 
   for each row 
begin  
   if inserting then 
      if :NEW."SID" is null then 
         select SHOPINFO_SEQ.nextval into :NEW."SID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "ADMIN"."SHOPINFO_INCREMENT" ENABLE;
