--------------------------------------------------------
--  파일이 생성됨 - 월요일-5월-11-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence CHAIN_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ADMIN"."CHAIN_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MENUOPTION_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ADMIN"."MENUOPTION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MENU_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ADMIN"."MENU_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence POST_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ADMIN"."POST_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence QNA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ADMIN"."QNA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 101 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence RESERVATION_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ADMIN"."RESERVATION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SHOPINFO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ADMIN"."SHOPINFO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 121 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ACCOUNT
--------------------------------------------------------

  CREATE TABLE "ADMIN"."ACCOUNT" 
   (	"BUSINESSNUMBER" NUMBER, 
	"PASSWORD" VARCHAR2(40 BYTE), 
	"EMAIL" VARCHAR2(40 BYTE), 
	"PHONE" NUMBER, 
	"EMAILACCEPT" VARCHAR2(20 BYTE), 
	"SMSACCEPT" VARCHAR2(20 BYTE), 
	"BUSINESSNAME" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "ADMIN"."ACCOUNT"."BUSINESSNUMBER" IS '사업자번호';
   COMMENT ON COLUMN "ADMIN"."ACCOUNT"."PASSWORD" IS '비밀번호';
   COMMENT ON COLUMN "ADMIN"."ACCOUNT"."EMAIL" IS '이메일';
   COMMENT ON COLUMN "ADMIN"."ACCOUNT"."PHONE" IS '연락처';
   COMMENT ON COLUMN "ADMIN"."ACCOUNT"."EMAILACCEPT" IS '이메일수신여부';
   COMMENT ON COLUMN "ADMIN"."ACCOUNT"."SMSACCEPT" IS '문자수신여부';
   COMMENT ON COLUMN "ADMIN"."ACCOUNT"."BUSINESSNAME" IS '사업자명';
   COMMENT ON TABLE "ADMIN"."ACCOUNT"  IS '사업자 계정 테이블';
--------------------------------------------------------
--  DDL for Table CHAINS
--------------------------------------------------------

  CREATE TABLE "ADMIN"."CHAINS" 
   (	"CHAINNAME" VARCHAR2(20 BYTE), 
	"CHAINIMAGE" VARCHAR2(400 BYTE), 
	"CHAINDESC" VARCHAR2(1000 BYTE), 
	"SID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "ADMIN"."CHAINS"."CHAINNAME" IS '체인명';
   COMMENT ON COLUMN "ADMIN"."CHAINS"."CHAINIMAGE" IS '체인이미지';
   COMMENT ON COLUMN "ADMIN"."CHAINS"."CHAINDESC" IS '체인설명';
   COMMENT ON COLUMN "ADMIN"."CHAINS"."SID" IS 'SID';
--------------------------------------------------------
--  DDL for Table MENU
--------------------------------------------------------

  CREATE TABLE "ADMIN"."MENU" 
   (	"MENUNAME" VARCHAR2(20 BYTE), 
	"MENUPRICE" NUMBER, 
	"MENUIMAGE" VARCHAR2(400 BYTE), 
	"MENUDESC" VARCHAR2(1000 BYTE), 
	"MENUCATEGORY" VARCHAR2(20 BYTE), 
	"SHOPNAME" VARCHAR2(20 BYTE), 
	"BUSINESSNUMBER" NUMBER, 
	"SID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "ADMIN"."MENU"."MENUNAME" IS '메뉴이름';
   COMMENT ON COLUMN "ADMIN"."MENU"."MENUPRICE" IS '메뉴가격';
   COMMENT ON COLUMN "ADMIN"."MENU"."MENUIMAGE" IS '메뉴이미지';
   COMMENT ON COLUMN "ADMIN"."MENU"."MENUDESC" IS '메뉴설명';
   COMMENT ON COLUMN "ADMIN"."MENU"."MENUCATEGORY" IS '메뉴분류';
   COMMENT ON COLUMN "ADMIN"."MENU"."SHOPNAME" IS '상점이름';
   COMMENT ON COLUMN "ADMIN"."MENU"."BUSINESSNUMBER" IS '사업자번호';
   COMMENT ON COLUMN "ADMIN"."MENU"."SID" IS 'SID';
--------------------------------------------------------
--  DDL for Table MENUOPTION
--------------------------------------------------------

  CREATE TABLE "ADMIN"."MENUOPTION" 
   (	"OPTIONNAME" VARCHAR2(20 BYTE), 
	"MENUNAME" VARCHAR2(20 BYTE), 
	"MENUSID" NUMBER, 
	"OPTIONPRICE" NUMBER, 
	"OPTIONSID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "ADMIN"."MENUOPTION"."OPTIONNAME" IS '옵션이름';
   COMMENT ON COLUMN "ADMIN"."MENUOPTION"."MENUNAME" IS '메뉴이름';
   COMMENT ON COLUMN "ADMIN"."MENUOPTION"."MENUSID" IS '메뉴참조';
   COMMENT ON COLUMN "ADMIN"."MENUOPTION"."OPTIONPRICE" IS '옵션가격';
   COMMENT ON COLUMN "ADMIN"."MENUOPTION"."OPTIONSID" IS 'SID';
--------------------------------------------------------
--  DDL for Table POST
--------------------------------------------------------

  CREATE TABLE "ADMIN"."POST" 
   (	"WRITERNAME" VARCHAR2(20 BYTE), 
	"WRITERPHONE" NUMBER, 
	"MARK" VARCHAR2(20 BYTE), 
	"POSTCONTENT" VARCHAR2(1000 BYTE), 
	"WRITEDATE" VARCHAR2(1000 BYTE), 
	"SHOPNAME" VARCHAR2(20 BYTE), 
	"BUSINESSNUMBER" NUMBER, 
	"POSTREPLY" VARCHAR2(1000 BYTE), 
	"SID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "ADMIN"."POST"."WRITERNAME" IS '작성자이름';
   COMMENT ON COLUMN "ADMIN"."POST"."WRITERPHONE" IS '작성자연락처';
   COMMENT ON COLUMN "ADMIN"."POST"."MARK" IS '평점';
   COMMENT ON COLUMN "ADMIN"."POST"."POSTCONTENT" IS '후기내용';
   COMMENT ON COLUMN "ADMIN"."POST"."WRITEDATE" IS '작성날짜';
   COMMENT ON COLUMN "ADMIN"."POST"."SHOPNAME" IS '상점이름';
   COMMENT ON COLUMN "ADMIN"."POST"."BUSINESSNUMBER" IS '사업자번호';
   COMMENT ON COLUMN "ADMIN"."POST"."POSTREPLY" IS '후기답변';
   COMMENT ON COLUMN "ADMIN"."POST"."SID" IS 'SID';
--------------------------------------------------------
--  DDL for Table QNA
--------------------------------------------------------

  CREATE TABLE "ADMIN"."QNA" 
   (	"WRITERNAME" VARCHAR2(20 BYTE), 
	"WRITERPHONE" VARCHAR2(20 BYTE), 
	"TITLE" VARCHAR2(100 BYTE), 
	"WRITEDATE" VARCHAR2(1000 BYTE), 
	"CONTENT" VARCHAR2(1000 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"REPLYCONTENT" VARCHAR2(1000 BYTE), 
	"REPLYDATE" VARCHAR2(20 BYTE), 
	"SID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "ADMIN"."QNA"."WRITERNAME" IS '작성자이름';
   COMMENT ON COLUMN "ADMIN"."QNA"."WRITERPHONE" IS '작성자연락처';
   COMMENT ON COLUMN "ADMIN"."QNA"."TITLE" IS '제목';
   COMMENT ON COLUMN "ADMIN"."QNA"."WRITEDATE" IS '작성날짜';
   COMMENT ON COLUMN "ADMIN"."QNA"."CONTENT" IS '질문내용';
   COMMENT ON COLUMN "ADMIN"."QNA"."PASSWORD" IS '글비밀번호';
   COMMENT ON COLUMN "ADMIN"."QNA"."REPLYCONTENT" IS '답변내용';
   COMMENT ON COLUMN "ADMIN"."QNA"."REPLYDATE" IS '답변날짜';
   COMMENT ON COLUMN "ADMIN"."QNA"."SID" IS 'SID';
--------------------------------------------------------
--  DDL for Table RESERVATION
--------------------------------------------------------

  CREATE TABLE "ADMIN"."RESERVATION" 
   (	"NAME" VARCHAR2(20 BYTE), 
	"PHONE" NUMBER, 
	"SHOPNAME" VARCHAR2(20 BYTE), 
	"BUSINESSNUMBER" NUMBER, 
	"RESRVATIONMENU" VARCHAR2(20 BYTE), 
	"RESERVATIONTIME" VARCHAR2(20 BYTE), 
	"RESERVATIONDATE" VARCHAR2(20 BYTE), 
	"SID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "ADMIN"."RESERVATION"."NAME" IS '예약자이름';
   COMMENT ON COLUMN "ADMIN"."RESERVATION"."PHONE" IS '예약자 핸드폰 번호';
   COMMENT ON COLUMN "ADMIN"."RESERVATION"."SHOPNAME" IS '가게명';
   COMMENT ON COLUMN "ADMIN"."RESERVATION"."BUSINESSNUMBER" IS '사업자번호';
   COMMENT ON COLUMN "ADMIN"."RESERVATION"."RESRVATIONMENU" IS '예약메뉴명';
   COMMENT ON COLUMN "ADMIN"."RESERVATION"."RESERVATIONTIME" IS '예약시간';
   COMMENT ON COLUMN "ADMIN"."RESERVATION"."RESERVATIONDATE" IS '예약날짜';
   COMMENT ON COLUMN "ADMIN"."RESERVATION"."SID" IS 'SID
';
--------------------------------------------------------
--  DDL for Table SHOPINFO
--------------------------------------------------------

  CREATE TABLE "ADMIN"."SHOPINFO" 
   (	"SHOPNAME" VARCHAR2(100 BYTE), 
	"BUSINESSNUMBER" NUMBER, 
	"SHOPADDRESS" VARCHAR2(1000 BYTE), 
	"SHOPPHONE" VARCHAR2(100 BYTE), 
	"SHOPCATEGORY" VARCHAR2(100 BYTE), 
	"SHOPINFO" VARCHAR2(1000 BYTE), 
	"SHOPCHAINNAME" VARCHAR2(1000 BYTE), 
	"SHOPMARK" VARCHAR2(20 BYTE), 
	"SHOPIMAGE" VARCHAR2(400 BYTE), 
	"SID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "ADMIN"."SHOPINFO"."SHOPNAME" IS '상점이름';
   COMMENT ON COLUMN "ADMIN"."SHOPINFO"."BUSINESSNUMBER" IS '사업자번호';
   COMMENT ON COLUMN "ADMIN"."SHOPINFO"."SHOPADDRESS" IS '상점주소';
   COMMENT ON COLUMN "ADMIN"."SHOPINFO"."SHOPPHONE" IS '상점연락처';
   COMMENT ON COLUMN "ADMIN"."SHOPINFO"."SHOPCATEGORY" IS '상점분류';
   COMMENT ON COLUMN "ADMIN"."SHOPINFO"."SHOPINFO" IS '상점설명';
   COMMENT ON COLUMN "ADMIN"."SHOPINFO"."SHOPCHAINNAME" IS '체인점이름';
   COMMENT ON COLUMN "ADMIN"."SHOPINFO"."SHOPMARK" IS '상점평점';
   COMMENT ON COLUMN "ADMIN"."SHOPINFO"."SHOPIMAGE" IS '상점이미지';
   COMMENT ON COLUMN "ADMIN"."SHOPINFO"."SID" IS 'SID';
REM INSERTING into ADMIN.ACCOUNT
SET DEFINE OFF;
Insert into ADMIN.ACCOUNT (BUSINESSNUMBER,PASSWORD,EMAIL,PHONE,EMAILACCEPT,SMSACCEPT,BUSINESSNAME) values (484846,'1234','alliswe@jkashnejk',84485,'asd','asd','djwi');
Insert into ADMIN.ACCOUNT (BUSINESSNUMBER,PASSWORD,EMAIL,PHONE,EMAILACCEPT,SMSACCEPT,BUSINESSNAME) values (4848462,'123','alliswe@jkashnejk2',844852,'asd','asd','djwi2');
REM INSERTING into ADMIN.CHAINS
SET DEFINE OFF;
Insert into ADMIN.CHAINS (CHAINNAME,CHAINIMAGE,CHAINDESC,SID) values ('CAFEBENE','/AppleWeb/Images/Business/Chains/cafebeneLOGO.png','카페베네 커피 전문점',22);
Insert into ADMIN.CHAINS (CHAINNAME,CHAINIMAGE,CHAINDESC,SID) values ('이름','이미지 경로','설명',6);
Insert into ADMIN.CHAINS (CHAINNAME,CHAINIMAGE,CHAINDESC,SID) values ('ANGELINUS','/AppleWeb/Images/Business/Chains/angelinus.jpg','엔제리너스 커피 전문점',23);
Insert into ADMIN.CHAINS (CHAINNAME,CHAINIMAGE,CHAINDESC,SID) values ('TWOSOMEPLACE','/AppleWeb/Images/Business/Chains/atwosomeplace.jpg','투썸플레이스 커피 전문점',24);
Insert into ADMIN.CHAINS (CHAINNAME,CHAINIMAGE,CHAINDESC,SID) values ('NONE','NONE','NONE',41);
Insert into ADMIN.CHAINS (CHAINNAME,CHAINIMAGE,CHAINDESC,SID) values ('이름2','이미지 경로','설명',8);
Insert into ADMIN.CHAINS (CHAINNAME,CHAINIMAGE,CHAINDESC,SID) values ('STARBUCKS','/AppleWeb/Images/Business/Chains/StarbucksLOGO.png','스타벅스 커피 전문점',21);
REM INSERTING into ADMIN.MENU
SET DEFINE OFF;
REM INSERTING into ADMIN.MENUOPTION
SET DEFINE OFF;
REM INSERTING into ADMIN.POST
SET DEFINE OFF;
REM INSERTING into ADMIN.QNA
SET DEFINE OFF;
Insert into ADMIN.QNA (WRITERNAME,WRITERPHONE,TITLE,WRITEDATE,CONTENT,PASSWORD,REPLYCONTENT,REPLYDATE,SID) values ('블랙','010-5465-8956','테스트','Fri May 08 10:02:58 KST 2015','가나다라마바사','1234',null,null,61);
Insert into ADMIN.QNA (WRITERNAME,WRITERPHONE,TITLE,WRITEDATE,CONTENT,PASSWORD,REPLYCONTENT,REPLYDATE,SID) values ('김길동','010000000','테스트','Fri May 08 10:50:58 KST 2015','ㅂㅈㄷㅂㅈㄷㅂㅈㄷㅂㅈㄷ','1234',null,null,66);
Insert into ADMIN.QNA (WRITERNAME,WRITERPHONE,TITLE,WRITEDATE,CONTENT,PASSWORD,REPLYCONTENT,REPLYDATE,SID) values ('홍길동','010-****-****','문의함','2015.4.30','ㅁㄴ이러ㅣㅏ넝리ㅏㅓ니러닝러ㅏㅣㅁㄴ어리ㅏㅓ','1234','1ㅁㄴㅇㄹㄴㅁㅇㄹㄴㅁㅇㄹㄴㅁㅇㄹㄴㅇ','2015.5.2',4);
Insert into ADMIN.QNA (WRITERNAME,WRITERPHONE,TITLE,WRITEDATE,CONTENT,PASSWORD,REPLYCONTENT,REPLYDATE,SID) values ('홍길동1','0100000000','테스트','Fri May 08 11:35:21 KST 2015','123123','1234',null,null,68);
Insert into ADMIN.QNA (WRITERNAME,WRITERPHONE,TITLE,WRITEDATE,CONTENT,PASSWORD,REPLYCONTENT,REPLYDATE,SID) values ('asd','12312','asd','Fri May 08 11:41:53 KST 2015','asda','1234',null,null,74);
Insert into ADMIN.QNA (WRITERNAME,WRITERPHONE,TITLE,WRITEDATE,CONTENT,PASSWORD,REPLYCONTENT,REPLYDATE,SID) values ('이희규','01023232323','어렵다','Fri May 08 12:05:19 KST 2015','많이 많이 복잡하다','1234',null,null,76);
Insert into ADMIN.QNA (WRITERNAME,WRITERPHONE,TITLE,WRITEDATE,CONTENT,PASSWORD,REPLYCONTENT,REPLYDATE,SID) values ('123','123','123','Fri May 08 12:10:32 KST 2015','123','1231',null,null,77);
Insert into ADMIN.QNA (WRITERNAME,WRITERPHONE,TITLE,WRITEDATE,CONTENT,PASSWORD,REPLYCONTENT,REPLYDATE,SID) values ('서웅','010-****-654654','테스트','Mon May 11 14:39:18 KST 2015','ㅂㅈㄷㅂㅈㄷ','1234',null,null,81);
REM INSERTING into ADMIN.RESERVATION
SET DEFINE OFF;
REM INSERTING into ADMIN.SHOPINFO
SET DEFINE OFF;
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('엔제리너스 이대점',1112233333,'서울 서대문구 대현동 60-8번지 F2~3','02-362-8401','CAFE','오전 07:00~ 오후 23:00','ANGELINUS','3.0','/AppleWeb/Images/Business/Shops/1112233333/엔제리너스 이대점.jpg',4);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('스타벅스 이대점',1112233333,'서울 서대문구 대현동 54-4','02-758-8001','CAFE','아름다운 사람들의 매장, 스타벅스커피 코리아 1호 이대점입니다. ','STARBUCKS','3.5','/AppleWeb/Images/Business/Shops/1112233333/스타벅스 이대점.jpg',2);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('스타벅스 신촌점',1112233333,'서울 서대문구 창천동 18-55 즐거운빌딩 1,2,3층','02-758-8035','CAFE','신촌의 랜드마크, 만남의 장소 신촌에서 따듯하고 정겨운 파트너들을 만나고 싶으시다면 신촌점으로 놀러오세요!! ','STARBUCKS','4.0','/AppleWeb/Images/Business/Shops/1112233333/스타벅스 신촌점.jpg',3);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('엔제리너스 강남역점',1112233333,'서울 서초구 서초대로77길 24','02-3478-9091','CAFE','2호선 강남역10번 출구 / 지오다노 뒷편 골목 ','ANGELINUS','4.2','/AppleWeb/Images/Business/Chains/angelinus.jpg',5);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('cafebene 이대정문점',1112233333,'서울시 서대문구 대현동 60-60?','02-392-6232','CAFE','북카페/ WIFI 및 PC 사용 가능 매장/ 우산 대여 가능 매장/ 노트북 대여 가능 매장/','CAFEBENE','0','/AppleWeb/Images/Business/Chains/cafebeneLOGO.png',21);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('cafebene 신촌로점',1112233333,'서울시 서대문구 창천동 20-26?','070-4259-6232','CAFE','북카페/ WIFI 및 PC 사용 가능 매장/ 우산 대여 가능 매장/','CAFEBENE','0','/AppleWeb/Images/Business/Chains/cafebeneLOGO.png',22);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('cafebene 신촌대로점',1112233333,'서울시 마포구 동교동 185-23?','02-326-6232','CAFE','북카페/ 세미나실 & 미팅룸 보유 매장/ WIFI 및 PC 사용 가능 매장/ 우산 대여 가능 매장/','CAFEBENE','0','/AppleWeb/Images/Business/Chains/cafebeneLOGO.png',23);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('cafebene 신촌현대점',1112233333,'서울시 서대문구 창천동 57-24?','02-335-6232','CAFE','북카페/ WIFI 및 PC 사용 가능 매장/ 우산 대여 가능 매장/','CAFEBENE','0','/AppleWeb/Images/Business/Chains/cafebeneLOGO.png',24);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('한식점 1',1112233333,'서울특별시 서초구 서초3동 1451-9','02-0000-0000','KOREANFOOD','한식','NONE','0','/AppleWeb/Apple/',27);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('한식점 2',1112233333,'서울특별시 서초구 서초3동 1451-9','02-0000-0000','KOREANFOOD','한식','NONE','0','/AppleWeb/Apple/',28);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('한식점 3',1112233333,'서울특별시 서초구 서초3동 1451-9','02-0000-0000','KOREANFOOD','한식','NONE','0','/AppleWeb/Apple/',29);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('한식점 4',1112233333,'서울특별시 서초구 서초3동 1451-9','02-0000-0000','KOREANFOOD','한식','NONE','0','/AppleWeb/Apple/',30);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('한식점 5',1112233333,'서울특별시 서초구 서초3동 1451-9','02-0000-0000','KOREANFOOD','한식','NONE','0','/AppleWeb/Apple/',31);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('한식점 6',1112233333,'서울특별시 서초구 서초3동 1451-9','02-0000-0000','KOREANFOOD','한식','NONE','0','/AppleWeb/Apple/',32);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('한식점 7',1112233333,'서울특별시 서초구 서초3동 1451-9','02-0000-0000','KOREANFOOD','한식','NONE','0','/AppleWeb/Apple/',33);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('한식점 8',1112233333,'서울특별시 서초구 서초3동 1451-9','02-0000-0000','KOREANFOOD','한식','NONE','0','/AppleWeb/Apple/',34);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('한식점 9',1112233333,'서울특별시 서초구 서초3동 1451-9','02-0000-0000','KOREANFOOD','한식','NONE','0','/AppleWeb/Apple/',35);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('한식점 10',1112233333,'서울특별시 서초구 서초3동 1451-9','02-0000-0000','KOREANFOOD','한식','NONE','0','/AppleWeb/Apple/',36);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('한식점 11',1112233333,'서울특별시 서초구 서초3동 1451-9','02-0000-0000','KOREANFOOD','한식','NONE','0','/AppleWeb/Apple/',37);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('한식점 12',1112233333,'서울특별시 서초구 서초3동 1451-9','02-0000-0000','KOREANFOOD','한식','NONE','0','/AppleWeb/Apple/',38);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('한식점 13',1112233333,'서울특별시 서초구 서초3동 1451-9','02-0000-0000','KOREANFOOD','한식','NONE','0','/AppleWeb/Apple/',39);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('한식점 14',1112233333,'서울특별시 서초구 서초3동 1451-9','02-0000-0000','KOREANFOOD','한식','NONE','0','/AppleWeb/Apple/',40);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('한식점 15',1112233333,'서울특별시 서초구 서초3동 1451-9','02-0000-0000','KOREANFOOD','한식','NONE','0','/AppleWeb/Apple/',41);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('한식점 16',1112233333,'서울특별시 서초구 서초3동 1451-9','02-0000-0000','KOREANFOOD','한식','NONE','0','/AppleWeb/Apple/',42);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('중식점 1',1112233333,'서울특별시 서초구 서초3동 1459-8 정풍빌딩 1층','02-0000-0000','CHINESEFOOD','중식','NONE','0','/AppleWeb/Apple/',43);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('중식점 2',1112233333,'서울특별시 서초구 서초3동 1459-8 정풍빌딩 1층','02-0000-0000','CHINESEFOOD','중식','NONE','0','/AppleWeb/Apple/',44);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('중식점 3',1112233333,'서울특별시 서초구 서초3동 1459-8 정풍빌딩 1층','02-0000-0000','CHINESEFOOD','중식','NONE','0','/AppleWeb/Apple/',45);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('중식점 4',1112233333,'서울특별시 서초구 서초3동 1459-8 정풍빌딩 1층','02-0000-0000','CHINESEFOOD','중식','NONE','0','/AppleWeb/Apple/',46);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('중식점 5',1112233333,'서울특별시 서초구 서초3동 1459-8 정풍빌딩 1층','02-0000-0000','CHINESEFOOD','중식','NONE','0','/AppleWeb/Apple/',47);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('중식점 6',1112233333,'서울특별시 서초구 서초3동 1459-8 정풍빌딩 1층','02-0000-0000','CHINESEFOOD','중식','NONE','0','/AppleWeb/Apple/',48);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('중식점 7',1112233333,'서울특별시 서초구 서초3동 1459-8 정풍빌딩 1층','02-0000-0000','CHINESEFOOD','중식','NONE','0','/AppleWeb/Apple/',49);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('중식점 8',1112233333,'서울특별시 서초구 서초3동 1459-8 정풍빌딩 1층','02-0000-0000','CHINESEFOOD','중식','NONE','0','/AppleWeb/Apple/',50);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('중식점 9',1112233333,'서울특별시 서초구 서초3동 1459-8 정풍빌딩 1층','02-0000-0000','CHINESEFOOD','중식','NONE','0','/AppleWeb/Apple/',51);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('중식점 10',1112233333,'서울특별시 서초구 서초3동 1459-8 정풍빌딩 1층','02-0000-0000','CHINESEFOOD','중식','NONE','0','/AppleWeb/Apple/',52);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('중식점 11',1112233333,'서울특별시 서초구 서초3동 1459-8 정풍빌딩 1층','02-0000-0000','CHINESEFOOD','중식','NONE','0','/AppleWeb/Apple/',53);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('중식점 12',1112233333,'서울특별시 서초구 서초3동 1459-8 정풍빌딩 1층','02-0000-0000','CHINESEFOOD','중식','NONE','0','/AppleWeb/Apple/',54);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('일식점 1',1112233333,'서울특별시 서초구 서초동 1627-5','02-0000-0000','JAPANESEFOOD','일식','NONE','0','/AppleWeb/Apple/',55);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('일식점 2',1112233333,'서울특별시 서초구 서초동 1627-5','02-0000-0000','JAPANESEFOOD','일식','NONE','0','/AppleWeb/Apple/',56);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('일식점 3',1112233333,'서울특별시 서초구 서초동 1627-5','02-0000-0000','JAPANESEFOOD','일식','NONE','0','/AppleWeb/Apple/',57);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('일식점 4',1112233333,'서울특별시 서초구 서초동 1627-5','02-0000-0000','JAPANESEFOOD','일식','NONE','0','/AppleWeb/Apple/',58);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('일식점 5',1112233333,'서울특별시 서초구 서초동 1627-5','02-0000-0000','JAPANESEFOOD','일식','NONE','0','/AppleWeb/Apple/',59);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('일식점 6',1112233333,'서울특별시 서초구 서초동 1627-5','02-0000-0000','JAPANESEFOOD','일식','NONE','0','/AppleWeb/Apple/',60);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('일식점 7',1112233333,'서울특별시 서초구 서초동 1627-5','02-0000-0000','JAPANESEFOOD','일식','NONE','0','/AppleWeb/Apple/',61);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('일식점 8',1112233333,'서울특별시 서초구 서초동 1627-5','02-0000-0000','JAPANESEFOOD','일식','NONE','0','/AppleWeb/Apple/',62);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('일식점 9',1112233333,'서울특별시 서초구 서초동 1627-5','02-0000-0000','JAPANESEFOOD','일식','NONE','0','/AppleWeb/Apple/',63);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('일식점 10',1112233333,'서울특별시 서초구 서초동 1627-5','02-0000-0000','JAPANESEFOOD','일식','NONE','0','/AppleWeb/Apple/',64);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('일식점 11',1112233333,'서울특별시 서초구 서초동 1627-5','02-0000-0000','JAPANESEFOOD','일식','NONE','0','/AppleWeb/Apple/',65);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('일식점 12',1112233333,'서울특별시 서초구 서초동 1627-5','02-0000-0000','JAPANESEFOOD','일식','NONE','0','/AppleWeb/Apple/',66);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('일식점 13',1112233333,'서울특별시 서초구 서초동 1627-5','02-0000-0000','JAPANESEFOOD','일식','NONE','0','/AppleWeb/Apple/',67);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('일식점 14',1112233333,'서울특별시 서초구 서초동 1627-5','02-0000-0000','JAPANESEFOOD','일식','NONE','0','/AppleWeb/Apple/',68);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('일식점 15',1112233333,'서울특별시 서초구 서초동 1627-5','02-0000-0000','JAPANESEFOOD','일식','NONE','0','/AppleWeb/Apple/',69);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('양식점 1',1112233333,'서울특별시 강남구 역삼동 820-9','02-0000-0000','WESTERNFOOD','양식','NONE','0','/AppleWeb/Apple/',70);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('양식점 2',1112233333,'서울특별시 강남구 역삼동 820-9','02-0000-0000','WESTERNFOOD','양식','NONE','0','/AppleWeb/Apple/',71);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('양식점 3',1112233333,'서울특별시 강남구 역삼동 820-9','02-0000-0000','WESTERNFOOD','양식','NONE','0','/AppleWeb/Apple/',72);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('양식점 4',1112233333,'서울특별시 강남구 역삼동 820-9','02-0000-0000','WESTERNFOOD','양식','NONE','0','/AppleWeb/Apple/',73);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('양식점 5',1112233333,'서울특별시 강남구 역삼동 820-9','02-0000-0000','WESTERNFOOD','양식','NONE','0','/AppleWeb/Apple/',74);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('양식점 6',1112233333,'서울특별시 강남구 역삼동 820-9','02-0000-0000','WESTERNFOOD','양식','NONE','0','/AppleWeb/Apple/',75);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('양식점 7',1112233333,'서울특별시 강남구 역삼동 820-9','02-0000-0000','WESTERNFOOD','양식','NONE','0','/AppleWeb/Apple/',76);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('양식점 8',1112233333,'서울특별시 강남구 역삼동 820-9','02-0000-0000','WESTERNFOOD','양식','NONE','0','/AppleWeb/Apple/',77);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('양식점 9',1112233333,'서울특별시 강남구 역삼동 820-9','02-0000-0000','WESTERNFOOD','양식','NONE','0','/AppleWeb/Apple/',78);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('양식점 10',1112233333,'서울특별시 강남구 역삼동 820-9','02-0000-0000','WESTERNFOOD','양식','NONE','0','/AppleWeb/Apple/',79);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('양식점 11',1112233333,'서울특별시 강남구 역삼동 820-9','02-0000-0000','WESTERNFOOD','양식','NONE','0','/AppleWeb/Apple/',80);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('양식점 12',1112233333,'서울특별시 강남구 역삼동 820-9','02-0000-0000','WESTERNFOOD','양식','NONE','0','/AppleWeb/Apple/',81);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('양식점 13',1112233333,'서울특별시 강남구 역삼동 820-9','02-0000-0000','WESTERNFOOD','양식','NONE','0','/AppleWeb/Apple/',82);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('양식점 14',1112233333,'서울특별시 강남구 역삼동 820-9','02-0000-0000','WESTERNFOOD','양식','NONE','0','/AppleWeb/Apple/',83);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('분식점 1',1112233333,'서울특별시 강남구 논현동 187-4','02-0000-0000','FLOURFOOD','분식','NONE','0','/AppleWeb/Apple/',84);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('분식점 2',1112233333,'서울특별시 강남구 논현동 187-4','02-0000-0000','FLOURFOOD','분식','NONE','0','/AppleWeb/Apple/',85);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('분식점 3',1112233333,'서울특별시 강남구 논현동 187-4','02-0000-0000','FLOURFOOD','분식','NONE','0','/AppleWeb/Apple/',86);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('분식점 4',1112233333,'서울특별시 강남구 논현동 187-4','02-0000-0000','FLOURFOOD','분식','NONE','0','/AppleWeb/Apple/',87);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('분식점 5',1112233333,'서울특별시 강남구 논현동 187-4','02-0000-0000','FLOURFOOD','분식','NONE','0','/AppleWeb/Apple/',88);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('분식점 6',1112233333,'서울특별시 강남구 논현동 187-4','02-0000-0000','FLOURFOOD','분식','NONE','0','/AppleWeb/Apple/',89);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('분식점 7',1112233333,'서울특별시 강남구 논현동 187-4','02-0000-0000','FLOURFOOD','분식','NONE','0','/AppleWeb/Apple/',90);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('분식점 8',1112233333,'서울특별시 강남구 논현동 187-4','02-0000-0000','FLOURFOOD','분식','NONE','0','/AppleWeb/Apple/',91);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('분식점 9',1112233333,'서울특별시 강남구 논현동 187-4','02-0000-0000','FLOURFOOD','분식','NONE','0','/AppleWeb/Apple/',92);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('분식점 10',1112233333,'서울특별시 강남구 논현동 187-4','02-0000-0000','FLOURFOOD','분식','NONE','0','/AppleWeb/Apple/',93);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('분식점 11',1112233333,'서울특별시 강남구 논현동 187-4','02-0000-0000','FLOURFOOD','분식','NONE','0','/AppleWeb/Apple/',94);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('분식점 12',1112233333,'서울특별시 강남구 논현동 187-4','02-0000-0000','FLOURFOOD','분식','NONE','0','/AppleWeb/Apple/',95);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('분식점 13',1112233333,'서울특별시 강남구 논현동 187-4','02-0000-0000','FLOURFOOD','분식','NONE','0','/AppleWeb/Apple/',96);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('분식점 14',1112233333,'서울특별시 강남구 논현동 187-4','02-0000-0000','FLOURFOOD','분식','NONE','0','/AppleWeb/Apple/',97);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('분식점 15',1112233333,'서울특별시 강남구 논현동 187-4','02-0000-0000','FLOURFOOD','분식','NONE','0','/AppleWeb/Apple/',98);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('분식점 16',1112233333,'서울특별시 강남구 논현동 187-4','02-0000-0000','FLOURFOOD','분식','NONE','0','/AppleWeb/Apple/',99);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('분식점 17',1112233333,'서울특별시 강남구 논현동 187-4','02-0000-0000','FLOURFOOD','분식','NONE','0','/AppleWeb/Apple/',100);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('분식점 18',1112233333,'서울특별시 강남구 논현동 187-4','02-0000-0000','FLOURFOOD','분식','NONE','0','/AppleWeb/Apple/',101);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('분식점 19',1112233333,'서울특별시 강남구 논현동 187-4','02-0000-0000','FLOURFOOD','분식','NONE','0','/AppleWeb/Apple/',102);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('분식점 20',1112233333,'서울특별시 강남구 논현동 187-4','02-0000-0000','FLOURFOOD','분식','NONE','0','/AppleWeb/Apple/',103);
Insert into ADMIN.SHOPINFO (SHOPNAME,BUSINESSNUMBER,SHOPADDRESS,SHOPPHONE,SHOPCATEGORY,SHOPINFO,SHOPCHAINNAME,SHOPMARK,SHOPIMAGE,SID) values ('분식점 21',1112233333,'서울특별시 강남구 논현동 187-4','02-0000-0000','FLOURFOOD','분식','NONE','0','/AppleWeb/Apple/',104);
--------------------------------------------------------
--  DDL for Index CHAINS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."CHAINS_PK" ON "ADMIN"."CHAINS" ("CHAINNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MENU_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."MENU_PK" ON "ADMIN"."MENU" ("SID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index QNA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."QNA_PK" ON "ADMIN"."QNA" ("SID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ACCOUNT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."ACCOUNT_PK" ON "ADMIN"."ACCOUNT" ("BUSINESSNUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SHOPINFO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SHOPINFO_PK" ON "ADMIN"."SHOPINFO" ("BUSINESSNUMBER", "SHOPNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MENUOPTION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."MENUOPTION_PK" ON "ADMIN"."MENUOPTION" ("OPTIONSID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RESERVATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."RESERVATION_PK" ON "ADMIN"."RESERVATION" ("SID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index POST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."POST_PK" ON "ADMIN"."POST" ("SID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ACCOUNT
--------------------------------------------------------

  ALTER TABLE "ADMIN"."ACCOUNT" MODIFY ("BUSINESSNAME" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."ACCOUNT" MODIFY ("SMSACCEPT" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."ACCOUNT" MODIFY ("EMAILACCEPT" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."ACCOUNT" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."ACCOUNT" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."ACCOUNT" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."ACCOUNT" ADD CONSTRAINT "ACCOUNT_PK" PRIMARY KEY ("BUSINESSNUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ADMIN"."ACCOUNT" MODIFY ("BUSINESSNUMBER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table QNA
--------------------------------------------------------

  ALTER TABLE "ADMIN"."QNA" ADD CONSTRAINT "QNA_PK" PRIMARY KEY ("SID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ADMIN"."QNA" MODIFY ("SID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."QNA" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."QNA" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."QNA" MODIFY ("WRITEDATE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."QNA" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."QNA" MODIFY ("WRITERPHONE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."QNA" MODIFY ("WRITERNAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SHOPINFO
--------------------------------------------------------

  ALTER TABLE "ADMIN"."SHOPINFO" MODIFY ("SID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SHOPINFO" ADD CONSTRAINT "SHOPINFO_PK" PRIMARY KEY ("BUSINESSNUMBER", "SHOPNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ADMIN"."SHOPINFO" MODIFY ("SHOPIMAGE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SHOPINFO" MODIFY ("SHOPMARK" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SHOPINFO" MODIFY ("SHOPCHAINNAME" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SHOPINFO" MODIFY ("SHOPINFO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SHOPINFO" MODIFY ("SHOPCATEGORY" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SHOPINFO" MODIFY ("SHOPPHONE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SHOPINFO" MODIFY ("SHOPADDRESS" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SHOPINFO" MODIFY ("BUSINESSNUMBER" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SHOPINFO" MODIFY ("SHOPNAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MENUOPTION
--------------------------------------------------------

  ALTER TABLE "ADMIN"."MENUOPTION" ADD CONSTRAINT "MENUOPTION_PK" PRIMARY KEY ("OPTIONSID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ADMIN"."MENUOPTION" MODIFY ("OPTIONSID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MENUOPTION" MODIFY ("MENUSID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MENUOPTION" MODIFY ("OPTIONPRICE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MENUOPTION" MODIFY ("MENUNAME" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MENUOPTION" MODIFY ("OPTIONNAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESERVATION
--------------------------------------------------------

  ALTER TABLE "ADMIN"."RESERVATION" ADD CONSTRAINT "RESERVATION_PK" PRIMARY KEY ("SID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ADMIN"."RESERVATION" MODIFY ("SID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."RESERVATION" MODIFY ("RESERVATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."RESERVATION" MODIFY ("RESERVATIONTIME" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."RESERVATION" MODIFY ("RESRVATIONMENU" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."RESERVATION" MODIFY ("BUSINESSNUMBER" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."RESERVATION" MODIFY ("SHOPNAME" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."RESERVATION" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."RESERVATION" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table POST
--------------------------------------------------------

  ALTER TABLE "ADMIN"."POST" ADD CONSTRAINT "POST_PK" PRIMARY KEY ("SID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ADMIN"."POST" MODIFY ("SID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."POST" MODIFY ("POSTREPLY" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."POST" MODIFY ("BUSINESSNUMBER" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."POST" MODIFY ("SHOPNAME" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."POST" MODIFY ("WRITEDATE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."POST" MODIFY ("POSTCONTENT" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."POST" MODIFY ("MARK" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."POST" MODIFY ("WRITERPHONE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."POST" MODIFY ("WRITERNAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CHAINS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."CHAINS" MODIFY ("SID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."CHAINS" ADD CONSTRAINT "CHAINS_PK" PRIMARY KEY ("CHAINNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ADMIN"."CHAINS" MODIFY ("CHAINDESC" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."CHAINS" MODIFY ("CHAINIMAGE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."CHAINS" MODIFY ("CHAINNAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MENU
--------------------------------------------------------

  ALTER TABLE "ADMIN"."MENU" ADD CONSTRAINT "MENU_PK" PRIMARY KEY ("SID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ADMIN"."MENU" MODIFY ("SID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MENU" MODIFY ("BUSINESSNUMBER" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MENU" MODIFY ("SHOPNAME" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MENU" MODIFY ("MENUCATEGORY" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MENU" MODIFY ("MENUDESC" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MENU" MODIFY ("MENUIMAGE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MENU" MODIFY ("MENUPRICE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MENU" MODIFY ("MENUNAME" NOT NULL ENABLE);
--------------------------------------------------------
--  DDL for Trigger CHAINS_AUTOINCREMENT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ADMIN"."CHAINS_AUTOINCREMENT" 
   before insert on "ADMIN"."CHAINS" 
   for each row 
begin  
   if inserting then 
      if :NEW."SID" is null then 
         select CHAIN_SEQ.nextval into :NEW."SID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "ADMIN"."CHAINS_AUTOINCREMENT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MENUOPTION_AUTOINCREMENT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ADMIN"."MENUOPTION_AUTOINCREMENT" 
   before insert on "ADMIN"."MENUOPTION" 
   for each row 
begin  
   if inserting then 
      if :NEW."OPTIONSID" is null then 
         select MENUOPTION_SEQ.nextval into :NEW."OPTIONSID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "ADMIN"."MENUOPTION_AUTOINCREMENT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MENU_AUTOINCREMENT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ADMIN"."MENU_AUTOINCREMENT" 
   before insert on "ADMIN"."MENU" 
   for each row 
begin  
   if inserting then 
      if :NEW."SID" is null then 
         select MENU_SEQ.nextval into :NEW."SID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "ADMIN"."MENU_AUTOINCREMENT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger POST_AUTOINCREMENT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ADMIN"."POST_AUTOINCREMENT" 
   before insert on "ADMIN"."POST" 
   for each row 
begin  
   if inserting then 
      if :NEW."SID" is null then 
         select POST_SEQ.nextval into :NEW."SID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "ADMIN"."POST_AUTOINCREMENT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger QNA_AUTOINCREMENT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ADMIN"."QNA_AUTOINCREMENT" 
   before insert on "ADMIN"."QNA" 
   for each row 
begin  
   if inserting then 
      if :NEW."SID" is null then 
         select QNA_SEQ.nextval into :NEW."SID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "ADMIN"."QNA_AUTOINCREMENT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger RESERVATION_AUTOINCREMENT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ADMIN"."RESERVATION_AUTOINCREMENT" 
   before insert on "ADMIN"."RESERVATION" 
   for each row 
begin  
   if inserting then 
      if :NEW."SID" is null then 
         select RESERVATION_SEQ.nextval into :NEW."SID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "ADMIN"."RESERVATION_AUTOINCREMENT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SHOPINFO_INCREMENT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ADMIN"."SHOPINFO_INCREMENT" 
   before insert on "ADMIN"."SHOPINFO" 
   for each row 
begin  
   if inserting then 
      if :NEW."SID" is null then 
         select SHOPINFO_SEQ.nextval into :NEW."SID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "ADMIN"."SHOPINFO_INCREMENT" ENABLE;
